<a href="https://colab.research.google.com/github/Saarza230/NNDN-ICP2/blob/main/NNDN%20ICP2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
class Employee:
    employee_count = 0

    def __init__(self, name, family, salary, department):
        self.name = name
        self.family = family
        self.salary = salary
        self.department = department
        Employee.employee_count += 1

    def average_salary(self, total_salary, total_employees):
        if total_employees > 0:
            return total_salary / total_employees
        else:
            return 0

    @classmethod
    def get_employee_count(cls):
        return cls.employee_count
class FulltimeEmployee(Employee):
    def __init__(self, name, family, salary, department, benefits):
        super().__init__(name, family, salary, department)
        self.benefits = benefits

emp1 = Employee("John", "Doe", 50000, "IT")
emp2 = Employee("Jane", "Smith", 60000, "HR")
fulltime_emp1 = FulltimeEmployee("Alice", "Johnson", 70000, "Finance", "Health Insurance")
fulltime_emp2 = FulltimeEmployee("Bob", "Brown", 80000, "Marketing", "Retirement Plan")

total_salary = emp1.salary + emp2.salary + fulltime_emp1.salary + fulltime_emp2.salary
total_employees = Employee.get_employee_count()
average = emp1.average_salary(total_salary, total_employees)

print(f"Total Employees: {total_employees}")
print(f"Average Salary: {average:.2f}")

print(f"Employee 1: Name={emp1.name}, Family={emp1.family}, Salary={emp1.salary}, Department={emp1.department}")
print(f"Employee 2: Name={emp2.name}, Family={emp2.family}, Salary={emp2.salary}, Department={emp2.department}")

print(f"Fulltime Employee 1: Name={fulltime_emp1.name}, Family={fulltime_emp1.family}, Salary={fulltime_emp1.salary}, Department={fulltime_emp1.department}, Benefits={fulltime_emp1.benefits}")
print(f"Fulltime Employee 2: Name={fulltime_emp2.name}, Family={fulltime_emp2.family}, Salary={fulltime_emp2.salary}, Department={fulltime_emp2.department}, Benefits={fulltime_emp2.benefits}")


Total Employees: 4
Average Salary: 65000.00
Employee 1: Name=John, Family=Doe, Salary=50000, Department=IT
Employee 2: Name=Jane, Family=Smith, Salary=60000, Department=HR
Fulltime Employee 1: Name=Alice, Family=Johnson, Salary=70000, Department=Finance, Benefits=Health Insurance
Fulltime Employee 2: Name=Bob, Family=Brown, Salary=80000, Department=Marketing, Benefits=Retirement Plan


In [3]:
import numpy as np

vector = np.random.uniform(1, 20, 20)

matrix = vector.reshape(4, 5)

max_values = matrix.max(axis=1, keepdims=True)

mask = (matrix == max_values)

matrix[mask] = 0

print("Original matrix:\n", vector.reshape(4, 5))
print("Matrix after replacing max values with 0:\n", matrix)


Original matrix:
 [[ 4.52531134  5.94156882  0.          6.2003302   4.58057515]
 [12.76890071  0.          1.06360734 13.80228786  5.74764322]
 [ 1.73528793  5.9155631  15.22279817  0.          8.67726885]
 [ 8.85999104  7.10518274 10.85208463 14.31679902  0.        ]]
Matrix after replacing max values with 0:
 [[ 4.52531134  5.94156882  0.          6.2003302   4.58057515]
 [12.76890071  0.          1.06360734 13.80228786  5.74764322]
 [ 1.73528793  5.9155631  15.22279817  0.          8.67726885]
 [ 8.85999104  7.10518274 10.85208463 14.31679902  0.        ]]
